Supports dark mode
mcplaynetwork/Ease pull request #8
Opened 2022-06-14 23:44 UTC by yukuto16

- Determine if it is dark mode from the device settings.
- The color was decided by my sense.
- It is basically the reverse of the original color.

2022-06-15 19:21 UTC, ViaSnake commented on default.hbs
> +    <link rel="stylesheet" href="{{asset "css/general/darkmode.css"}}">
Should be called by screen.css.

2022-06-15 19:24 UTC, ViaSnake commented on assets/css/general/darkmode.css
> +    --main-bg: #000;
What does main refer to? I don't think the variable name is appropriate.

2022-06-15 20:00 UTC, ViaSnake requested changes
![image](https://user-images.githubusercontent.com/6961187/173916253-534f7723-162e-42e8-b2c8-544e4a6b1cbf.png)
![image](https://user-images.githubusercontent.com/6961187/173916273-13886870-fc42-49e2-98ca-faf3242d15d0.png)

Tag is not in dark mode.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +  }
```suggestion
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    color: var(--light-gray-color);
  }
```

2022-06-15 20:00 UTC, viasnake commented on default.hbs
> +    <link rel="stylesheet" href="{{asset "css/general/darkmode.css"}}">
Should be called by screen.css.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +    --main-bg: #000;
What does main refer to?
I feel that a better naming exists.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +    --dark-gray-color: #1a1a1a;
I don't think it is necessary to overwrite it with the same value.
Was there a reason to overwrite?

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +  }
I think it is unnatural that this is handled in css/site/*.css, since it is originally handled in css/site/header.css.
However, I can't immediately think of the most optimal solution. If possible, it would be more naturaal to handle it in site.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +  }
I don't think it is necessary to overwrite it with the same value.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +  }
I don't think it is necessary to overwrite it with the same value.

2022-06-15 20:00 UTC, viasnake commented on assets/css/general/darkmode.css
> +    --main-bg: #000;
I don't think perfect black is suitable for design or visual purposes.
Personally, I prefer a milder black or some darker color that is easier to see. At least I find the current color scheme difficult to see in reverse.
As an example, for YouTube it is `#181818` `#21212121` `#3d3d3d` `#ffffff` `#aaaaa`; for Twitter it is `#15202B` `#192734` `#22303C` `#FFFFFFFF` `#8899A6`. Neither of these employs complete black. (It may be used as an accent.)

There is no right answer for the design, but we will need to consider a better color scheme.

Below is the Dark theme page of Material.io. It may be helpful.
https://material.io/design/color/dark-theme.html

2022-06-15 20:02 UTC, ViaSnake commented
When changing the color scheme, it may look better if you choose different color schemes for the header and body.

2022-06-18 06:19 UTC, ViaSnake commented
I did not notice this because I debugged locally, but no assets are being generated. You need to generate them and include them in the commit.

2022-06-24 22:17 UTC, closed without merging